### PR TITLE
unconvert: fix calling without arguments

### LINKED ISSUE #44: no arguments should mean . (again)
This is a bug that was reported previously as #8, and was fixed in #9, but regressed in #32.

`unconvert` without arguments should be the same as `unconvert .`, that is operate on the Go package in the current working directory.

This is the cause:

https://github.com/mdempsky/unconvert/blob/2f5dc3378ed3ba283f5125b8bb47f6ba672f879b/unconvert.go#L221-L224

Before #32 was applied, that code looked like this:

https://github.com/mdempsky/unconvert/blob/dc69f12fff3087ab405d3c0759549bb7a1dcfd3b/unconvert.go#L200-L203

The difference is that `gotool.ImportPaths([]string(nil))` returned `[]string{"."}`. This isn't the case after #32 replaced that with just `flag.Args()`.

Note that `packages.Load(cfg)` returns the same result as `packages.Load(cfg, ".")`, it loads the package in the current working directory. The current code just never reaches the call to `packages.Load`.

/cc @egonelbre @mvdan

P.S. I noticed this because of https://github.com/shurcooL/octicon/blob/9ff1a4cf27f4a918862c3ffbd24371b3aed18f9d/doc.go#L10.

### PR DESCRIPTION
**Pull request by egonelbre**
`unconvert` should default to current directory when there are no arguments. Apparently `packages.Load` does it already automatically. Remove the check for no arguments and add tests for the different cases.

Fixes #44

### CODE REVIEW

File: unconvert.go [hunk 1]
```diff
@@ -219,9 +219,6 @@ func main() {
 	}
 
 	importPaths := flag.Args()
```
Comment (dmitshur) [inline unconvert.go]: Consider renaming this variable to `patterns`, here, as well as in the functions `mergeEdits` and `computeEdits`. These arguments may be import path patterns, so `patterns` would more accurately describe what is being represented.

It would also match the parameter name of [`packages.Load`](https://godoc.org/golang.org/x/tools/go/packages#Load) where this slice eventually gets passed.

File: unconvert_test.go [hunk 2]
```diff
@@ -20,43 +20,61 @@ func TestBinary(t *testing.T) {
...
-	if err == nil {
-		t.Fatal("expected to quit with an error code")
+	tests := []struct {
+		name    string
+		workdir string
+		args    []string
+	}{
+		{"relative", ".", []string{"./testdata"}},
+		{"dot", "./testdata", []string{"."}},
+		{"no-args", "./testdata", []string{}},
```
Comment (dmitshur) [inline unconvert_test.go]: You can add another test case to do basic coverage of import path patterns:

```suggestion
		{"no-args", "./testdata", []string{}},
		{"pattern", "./testdata", []string{"./..."}},
```

File: unconvert.go (hunk 1 above)
Comment (dmitshur) [reply unconvert.go]: You can also add a comment like:

```suggestion
	patterns := flag.Args() // 0 or more import path patterns.
```

That'll make it more clear that it can be an empty slice, and that is okay.

Comment (egonelbre) [reply unconvert.go]: Fixed

File: unconvert_test.go (hunk 2 above)
Comment (egonelbre) [reply unconvert_test.go]: Added

**Comment by dmitshur** [comment]
Thank you for fixing this Egon!
